-- Lista 1 - a) Faça os scripts para a criação das tabelas, sem as constraints --

create table SUPPLIER (
	CDSUPPLIER INT NOT NULL,
	NMSUPPLIER VARCHAR(255),
	NRFONE NUMERIC(12),
)

CREATE TABLE PRODUCT (
	CDPRODUCT INT NOT NULL,
	NMPRODUCT VARCHAR(255),
	CDSUPPLIER INT NOT NULL,
	VLPRICE NUMERIC (10,2),
	QTSTOCK INT,
)

CREATE TABLE CUSTOMER(
	CDCUSTOMER INT NOT NULL,
	NMCUSTOMER VARCHAR(255),
	NRFONE NUMERIC(12),
	DSADRESS VARCHAR(255)
)

CREATE TABLE REQUEST (
  DTREQUEST DATE,
  CDREQUEST INT NOT NULL,
  DTDELIVER DATE,
  VLTOTAL NUMERIC(10 , 2)
)

CREATE TABLE PRODUCTREQUEST (
  CDREQUEST INT NOT NULL,
  CDPRODUCT INT NOT NULL,
  QTAMOUNT INT,
  VLUNITARY NUMERIC(10, 2)
)

-- Lista 1 - b) Faça um script para a criação das chaves primárias das tabelas criadas;

ALTER TABLE SUPPLIER ADD PRIMARY KEY (CDSUPPLIER)

ALTER TABLE PRODUCT ADD PRIMARY KEY (CDPRODUCT)

ALTER TABLE CUSTOMER ADD PRIMARY KEY (CDCUSTOMER)
  
ALTER TABLE REQUEST ADD PRIMARY KEY (CDREQUEST)

ALTER TABLE PRODUCTREQUEST ADD PRIMARY KEY (CDREQUEST, CDPRODUCT)


-- Lista 1 - c) Faça um script para criação das chaves secundárias das tabelas criadas



